name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn@4

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          node --max-old-space-size=4096 yarn build:storybook
        env:
          CI: true

      - name: Test
        run: |
          node --max-old-space-size=4096 yarn ci
        env:
          CI: true

      - name: Prepare and deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/storybook/@swimlane/ngx-graph
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          CI: true
